name: Goonzion Quartet
favicon: null
layout_spectrum: 0.56522
typography_spectrum: 0.20172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#4d5042'
    - '#c1cddb'
    - '#9c8017'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
