name: Goonzion Quartet
favicon: null
layout_spectrum: 0.56522
typography_spectrum: 0.20172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#b8b099'
    - '#403d36'
    - '#888689'
  brandStrength: 0
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
