name: Goonzion Quartet
favicon: null
layout_spectrum: 0.56522
typography_spectrum: 0.61712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#38343b'
    - '#b7b7b7'
    - '#6b6867'
    - '#9c9c9c'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
