name: Goonzion Quartet
favicon: null
layout_spectrum: 0.81084
typography_spectrum: 0.61188
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d2cd'
    - '#0e0e10'
    - '#fefefe'
    - '#808275'
    - '#58b98c'
  brandStrength: 1
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
