name: Goonzion Quartet
favicon: null
layout_spectrum: 0
typography_spectrum: 0.45551
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#910E15'
    - '#390404'
    - '#FFFFFA'
    - '#6E5B4B'
    - '#C5AD91'
  brandStrength: 0
  lightness: 0
  saturation: 0.881113
  rhythmicContrast: 0
purpose: []
