name: Goonzion Quartet
favicon: null
layout_spectrum: 0.21427855920046568
typography_spectrum: 0.61712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2c2d'
    - '#d04d39'
    - '#e2e3dd'
    - '#797a7e'
    - '#b3ae99'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
